name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "${{secrets.DOCKERPW}}" | docker login -u "mikoko" --password-stdin
        docker image build -t mikoko/aidockerimage:0.01 .
        docker push mikoko/aidockerimage:0.01
